import React from "react";
import BackButton from "./BackButton";
import TitleBar from "./title";
import Textbox from "./Textbox";
import "./Pages.css";

const AboutPage = () => {
  const linkStyle = {
    color: "#909090", // replace 'your-color' with your desired color
    textDecoration: "underline",
  };
  return (
    <><style jsx global>{`
      body {
        background: ${"#f8f8f8"};
      }
    `}</style><div className="container9">
        <BackButton />
        <TitleBar
          titleImage="/image 12.png"
          titleText="About Oro/Terms and Conditions"
          
        ></TitleBar>
        <div className="container2">
        <Textbox>
          <div className="textcontainer">
            <div className="subtitlecontainer">About Oro</div>
            <p>
              We're helping Indians unlock the value of their gold so the gold
              they bought as a product of scarcity can bring abundance to their
              lives!
            </p>
            <div className="subtitlecontainer">What do we do at Oro?</div>
            <p>
              We are building products and services that can help create a
              financial system that is more inclusive. There are 3 primary tenets
              based on which we build our products-trust, access and pricing.
            </p>
            <p>
              At Oro, we aspire to make gold in Indian households more valuable!
              <br></br>We ensure our products are simple and transparent, and
              build partnerships that embody trust. All of this, to provide
              convenience to the customer at cheapest possible costs. Indians own
              25,000 tonnes of gold, stored in their houses or bank lockers. Out
              of that, less than 1,500 tonnes contributes positively to India's
              GDP.{" "}
            </p>
            <p>
              Fun fact: 2,500 tonnes of gold is worth Rs.15 Lakh Crores
              (Rs.1,50,00,00,00,00,000).<br></br>Oro's mission is to help monetise
              the next 10%, or ~ 2,500 tonnes by leveraging technology,
              convenience and partnerships - boosting India's GDP by over 6%.
            </p>
            <div className="subtitlecontainer">Terms and Conditions</div>
            <p>
              This document is an electronic record in terms of the Information
              Technology Act, 2000 and rules there under as amended from time to
              time. This electronic record is generated by a computer system and
              does not require any physical or digital signatures for validation,
              consent or acceptance.
            </p>
            <p>
              These terms and conditions (“Terms”) of Orocorp Technologies Private
              Limited, a company incorporated under the provisions of the
              Companies Act, 2013, bearing company identification number
              U67190TN2020PTC135200 and having its registered office at No.10/1,
              Varadappan Street, West Mambalam, Chennai, Tamil Nadu, India, 600033
              (“Orocorp”, or “we”, or “us”, or “our”), govern your (“User” or
              “you” or “your”) usage of the Platform.{" "}
            </p>
            <p>
              These Terms also include our privacy policy available at
              orocorp.in/privacy-policy (“Privacy Policy”) and the Additional
              Terms and Conditions (defined below).
            </p>
            <ol>
              <font color="#454545">
                <li>Definitions</li>
                <li>
                  APPLICATION/APP:
                  <font color="#909090">
                    "Application/App" shall refer to the mobile application,
                    ‘OroMoney’ owned and operated by Orocorp.
                  </font>
                </li>
                <li>
                  APPLICABLE LAW:
                  <font color="#909090">
                    {" "}
                    “Applicable Law” means any statute, law, regulation,
                    ordinance, rule, judgment, notification, order, decree,
                    bye-law, permits, licenses, approvals, consents,
                    authorizations, government approvals, directives, guidelines,
                    requirements or other governmental restrictions, or any
                    similar form of decision of, or determination by, or any
                    interpretation, policy or administration, having the force of
                    law of any of the foregoing, by any governmental authority,
                    whether in effect as on the date of you agreeing to be bound
                    by these Terms or at any time thereafter.
                  </font>
                </li>
                <li>
                  ADDITIONAL TERMS AND CONDITIONS:
                  <font color="#909090">
                    “Additional Terms and Conditions” shall mean any guidelines,
                    additional terms, policies, or disclaimers made available or
                    issued by us, any third party or affiliate from time to time
                    in relation to the respective Services.
                  </font>{" "}
                </li>
                <li>
                  BORROWER:
                  <font color="#909090">
                    “Borrower” shall mean any User who avails a Credit Facility
                    from the Lenders through Orocorp.CREDIT FACILITY: "Credit
                    Facility" shall mean the loan or any other credit facility
                    that a User may avail through the Platform.
                  </font>
                </li>
                <li>
                  LOAN AGREEMENT:
                  <font color="#909090">
                    “Loan Agreement” shall mean any agreements or documentation
                    executed between the Lender and the Borrower pertaining to the
                    grant of a Credit Facility.
                  </font>{" "}
                </li>
                <li>
                  LENDER:
                  <font color="#909090">
                    “Lender” shall mean the regulated entity that extends the
                    Credit Facility to the Borrower through the Platform.
                  </font>
                </li>
                <li>
                  PERSONAL INFORMATION:
                  <font color="#909090">
                    "Personal information" shall have the meaning as ascribed to
                    it under the Information Technology (Reasonable security
                    practices and procedures and sensitive personal data or
                    information) Rules, 2011. For the sake of clarity, Personal
                    Information shall include sensitive personal information as
                    defined under the Information Technology (Reasonable security
                    practices and procedures and sensitive personal data or
                    information) Rules, 2011. PLATFORM: “Platform” shall mean the
                    Application and Website.
                  </font>
                </li>
                <li>
                  SERVICES:
                  <font color="#909090">
                    “Services” shall mean and include provision of the Platform by
                    us and the access to various products and services through the
                    Platform, as may be amended, added, or withdrawn by us from
                    time to time.
                  </font>
                </li>
                <li>
                  THIRD-PARTY SERVICES:
                  <font color="#909090">
                    “Third-Party Services” shall have the meaning as ascribed to
                    it under clause 4.3 below.
                  </font>
                </li>
                <li>
                  USER ACCOUNT:
                  <font color="#909090">
                    “User Account” shall mean the registered account of the User
                    with Orocorp for use and access of the Platform and the
                    Services.
                  </font>
                </li>
                <li>
                  WEBSITE:
                  <font color="#909090">
                    Website" shall refer to{" "}
                    <a href="https://orocorp.in/" style={linkStyle}>
                      www.orocorp.in,
                    </a>
                    <a href="https://oromoney.in/ " style={linkStyle}>
                      https://oromoney.in
                    </a>{" "}
                    and{" "}
                    <a href="https://orosafe.in/ " style={linkStyle}>
                      https://orosafe.in/
                    </a>{" "}
                    or such other website Orocorp notifies for the purposes of
                    these Terms.{" "}
                  </font>
                </li>
                <li>User Acknowledgment and Consent</li>
                <li>
                  <font color="#909090">
                    You acknowledge that by accessing the Platform and/or availing
                    the Services, you consent to be governed and bound by these
                    Terms. You acknowledge that by accessing the Platform and/or
                    availing the Services, you shall strictly abide by the Terms
                    detailed herein. If you do not agree to these Terms, you may
                    not access or use the Services or the Platform.
                  </font>
                </li>
                <li>Eligibility</li>
                <li>
                  <font color="#909090">
                    In order to assent to these Terms, you represent and warrant
                    that: (a) you have full legal capacity, right and authority to
                    agree to and be bound by these Terms, (b) you are at least 18
                    (eighteen) years of age or older, (c) you are an Indian
                    resident, (d) you have not been previously suspended or
                    removed by Orocorp or any of its affiliates from availing the
                    Services or have been disqualified from availing any Services,
                    (e) you are not barred or otherwise legally prohibited from
                    accessing or using the Services, and (f) you are not and will
                    not impersonate any person, entity or falsely state or
                    otherwise misrepresent such person’s or entity’s identity. A
                    person who is not competent to contract a minor, a person of
                    unsound mind, etc. shall not access this Platform and use the
                    Services without the consent of his or her guardian. The
                    guardian is presumed to have read these Terms to give consent
                    on behalf of a minor and shall be bound by these Terms. If at
                    any time, Orocorp is of the opinion that you do not satisfy
                    the eligibility criteria, including but not limited to any
                    misrepresentation, misuse of any Service or offers, fraudulent
                    or suspicious activities or transactions, Orocorp retains all
                    rights to disable your access to the Platform and/or suspend
                    your use of the Services with immediate effect.
                  </font>
                </li>
                <li>Services</li>
                <li>
                  <font color="#909090">
                    The Platform enables you to avail Credit Facilities by
                    facilitating your connection to the Lenders based on our
                    preliminary risk assessment, undertaken in accordance with the
                    Lenders’ instructions to us.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Access to Credit Facilities is subject to various criteria
                    determined by the relevant Lender at its sole discretion,
                    including but not limited to their credit policies, your
                    credit bureau report, and your successful completion of the
                    Know Your Customer (“KYC”) process prescribed by the relevant
                    Lender.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    The Platform may utilise services, content, documents, and
                    information owned by, licensed to, or otherwise made available
                    by a third party or our affiliates{" "}
                    <font color="#454545">(“Third Party Services”)</font> and the
                    Platform may also include links to the Third-Party Services.
                    You understand and acknowledge that Third Party Services are
                    the responsibility of the respective third-party or affiliate
                    that renders such Third Party Services. You further
                    acknowledge that your use of such Third-Party Services is
                    solely at your own risk.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    We make no representations and disclaim all warranties and
                    liabilities arising out of or pertaining to such Third-Party
                    Services including their accuracy or completeness. Should you
                    avail any Third-Party Service, you shall be governed and bound
                    by the Additional Terms and Conditions of the relevant third
                    party or the affiliate providing the Third-Party Service.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    We shall send all communications to our users by text
                    messages, electronic mails, WhatsApp messages, push
                    notifications and/or via other progressive technology in
                    connection with your access to the Platform, utilisation of
                    the Services and as part of our promotional and marketing
                    strategy. You agree to receive all messages, emails and/or
                    WhatsApp messages including transactional messages from us,
                    any third parties and our affiliates. We may use Third Party
                    Service providers to send alerts or to communicate with you.
                    You authorize us, our affiliates and other entities providing
                    Third Party Services to override the DND settings to reach out
                    to you over calls, SMS, emails, WhatsApp messages and any
                    other mode of communication. To the extent permissible under
                    Applicable Law, you agree that all documents, notices,
                    disclosures and other communications that we provide to you
                    electronically satisfy any legal requirement that such
                    communication be in writing.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You further acknowledge that you are responsible for the
                    contact details shared with us and shall update us immediately
                    on any change to your contact details
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You hereby agree and acknowledge that at any point of time we,
                    or a Third Party Service provider or our affiliates providing
                    any of the Services on the Platform, shall have the right to
                    reject any of your applications for availing any of the
                    Services provided on the Platform at our, the Third Party
                    Service provider’s or our affiliate’s sole discretion without
                    assigning any reason to you whatsoever, unless otherwise
                    required under Applicable Laws.
                  </font>
                </li>
                <li>User Account</li>
                <li>
                  <font color="#909090">
                    In order to avail the Services, you will be required to create
                    a User Account on the Platform by providing your details
                    including but not limited to your name, phone number, email
                    address, and date of birth. If you choose to create a User
                    Account, you agree to provide and maintain true, accurate, and
                    complete information about yourself as prompted on the
                    Platform and failure to do so shall constitute a breach of the
                    Terms, which may result in immediate termination or suspension
                    of your User Account at Orocorp’s sole discretion.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You are solely responsible for maintaining the confidentiality
                    of the User Account details and for any activity that occurs
                    through your User Account. You agree to immediately notify
                    Orocorp of any actual or suspected unauthorised use of your
                    User Account or any other breach of security. Orocorp will not
                    be liable for any losses or damages that may arise from your
                    failure to comply with the above-mentioned provisions or your
                    failure to ensure the confidentiality of your User Account or
                    password.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    We reserve the right to disable your access to the User
                    Account if, in our reasonable opinion, you are in breach of
                    any provision of the Terms or the Applicable Law or in the
                    event of any actual or suspected unauthorised access to your
                    User Account.
                  </font>
                </li>
                <li>
                  Verfification<br></br>
                  <font color="#909090">
                    You may be required to undertake certain additional processes
                    with us in order to avail the Services or in order for us to
                    establish your identity and undertake KYC processes. In this
                    regard, we may require you to share documents and information
                    <font color="#454545"> (“Documents”)</font> that may be
                    necessary for us to ascertain your eligibility to avail the
                    Services.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You authorise us, and any Third-Party Service providers we may
                    engage with, to process your Documents and ascertain your
                    eligibility to avail the Services. Any processing that we
                    undertake shall be in accordance with our Privacy Policy. You
                    agree that such processing may be subject to Additional Terms
                    and Conditions in the event a third-party processes
                    information under this Clause.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Further, you agree and acknowledge that we reserve the right
                    to undertake any enhanced due diligence measures (this may
                    include seeking any additional information, data, or
                    documentation (collectively,
                    <font color="#454545">“Additional Information”))</font>, (i)
                    either independently to satisfy ourselves; (ii) on directions
                    of the Lenders; or (iii) on behalf of the Third-Party Service
                    provider, to ensure your eligibility for the Services,
                    including Third-Party Services or for your continued use of
                    the Services, including Third-Party Services. You agree to
                    fully cooperate and share such Additional Information promptly
                    upon request, and further authorise us to process such
                    Additional Information.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You agree and warrant to provide true, complete, and
                    up-to-date Documents and Additional Information to us. If we
                    suspect that the Documents or the Additional Information
                    provided by you is unreliable or appears to be fraudulent or
                    deficient, then we reserve the right to not provide you the
                    Services, including Third-Party Services or allow use of the
                    Platform, as the case may be.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Orocorp does not accept any responsibility or liability for
                    any loss or damage that you may suffer or incur if any
                    information, documentation, material, or data provided to
                    avail the Services, including Third-Party Services, is
                    incorrect, incomplete, inaccurate, or misleading, or if you
                    fail to disclose any material fact.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    By continuing the usage of the Platform and the Services,
                    including Third-Party Services, you hereby represent that you
                    are not a Politically Exposed Person (“PEP”) as defined under
                    Applicable Law. In the event your PEP status changes, you
                    agree and undertake to immediately notify us in writing. You
                    further understand that as a PEP, you will be subject to
                    enhanced due diligence measures as may be required under the
                    Applicable Law and based on directions of the Lenders.
                  </font>
                </li>
                <li>Terms specific to Credit Facility</li>
                <li>
                  <font color="#909090">
                    Any Credit Facility made available to the Borrower by any
                    Lender shall be governed by the Loan Agreement, and we shall
                    neither be a party to the same, nor be liable or responsible
                    for the Lender’s actions or omissions under such terms.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    In case of a Credit Facility against the security of gold
                    jewellery or ornaments
                    <font color="#454545"> (“Gold Loan”)</font>, our
                    representatives shall visit your location to assess your gold
                    jewellery and collect the same for submission to the Lender.
                    The representative may also assist you with or carry out your
                    KYC or other processes as directed by the Lender. The Platform
                    will provide you the details of the representative assigned to
                    visit you and you agree that you will interact with only such
                    representative whose details are provided to you on the
                    Platform. We encourage you to verify the identity of such
                    representative and request the representative to display their
                    authorised Orocorp identity document. We shall not be
                    responsible for any loss, theft, or any other mishappening if
                    you do not verify the identity of the representatives.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    In case of a Gold Loan, the Borrower authorises Orocorp and
                    its affiliates or representatives to collect, assess, store,
                    carry, deliver, transfer or handle the gold jewellery provided
                    by the Borrower as the security for the Gold Loan in the
                    manner as permissible under Applicable Laws.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    The Borrower understands and agrees that Orocorp shall not be
                    held liable for any loss or theft of the gold jewellery or
                    ornaments provided as a security for the Credit Facility once
                    the same is submitted by Orocorp to the custody of the Lender.
                  </font>
                </li>
                <li>Your Responsibilities</li>
                <li>
                  <font color="#909090">
                    You will not use the Platform or avail the Services, including
                    Third-Party Services, for any purpose or in any manner except
                    as expressly permitted in these Terms. Without limiting the
                    generality of the preceding sentence, you shall not:
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    except as maybe provided hereunder, copy, display, upload,
                    modify, publish, transmit, update, create any derivative works
                    from or licence the Platform;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    use the Platform to transmit any data or send or upload any
                    material that belongs to another person and to which you do
                    not have any right;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    use the Platform to transmit any data or send or upload any
                    material that is grossly harmful, harassing, blasphemous,
                    defamatory, obscene, pornographic, libellous, invasive of
                    another’s privacy, hateful, or racially, ethnically
                    objectionable, disparaging, relating or encouraging money
                    laundering or gambling, or otherwise unlawful in any manner ;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    use the Platform to transmit any data or send or upload any
                    material that involves the transmission of (without
                    limitation) "junk mail", "chain letters", or unsolicited mass
                    mailing or "spamming" or unsolicited commercial advertisement
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    use any (without limitation) robot, spider, other automated
                    device, or manual process to monitor or copy the Platform or
                    any portion thereof;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    use the Platform to transmit any data or send or upload any
                    material that harms minors in any way;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    use the Platform to transmit any data or send or upload any
                    material that infringes any patent, trademark, copyright or
                    other proprietary rights;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    act in an abusive or threatening manner or use abusive or
                    threatening language on or through the Platform and/or disrupt
                    the experience of another user of the Platform;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    use the Platform to transmit any data or send or upload any
                    material that violates any Applicable Laws in any manner;use
                    the Platform to transmit any data or send or upload any
                    material that contains (without limitation) software viruses,
                    trojan horses, worms, timebombs, keystroke loggers, spyware,
                    adware, or any other harmful programmes or similar computer
                    code, files or programs designed to adversely affect the
                    operation of any computer software or hardware;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    engage in the systematic retrieval of content from the
                    Platform to create or compile, directly or indirectly, a
                    collection, compilation, database or directory;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    use the Platform or the Services in any unlawful manner, for
                    fraudulent or malicious activities, or in any manner
                    inconsistent with these Terms;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    use the Platform to transmit information or content that is
                    harmful to children or that impersonates another person, or
                    deceive or mislead any addressee about the origin of a
                    message, or knowingly and intentionally communicates any
                    misinformation or information which is patently false and
                    untrue or misleading in the nature or, in respect of any
                    business of the Indian government, is identified as fake or
                    false or misleading by the fact check unit of the Indian
                    government;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    use the Platform in a manner that threatens the unity,
                    integrity, defence, security, or sovereignty of India,
                    friendly relations with foreign states, or public order, or
                    cause incitement to the commission of any cognizable offence,
                    or prevent investigation of any offence, or insult another
                    nation in any manner;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    reverse engineer, decompile, or disassemble the Platform;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    use the Platform to publish any commercial material or content
                    (including, but not limited to, solicitation of funds,
                    advertising, or marketing of any good or services); or
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    take any action that may adversely affect the Services or
                    Platform.
                  </font>
                </li>
                <li>Disclaimer</li>
                <li>
                  <font color="#909090">
                    The use of the Platform or availing of Services is at your
                    sole risk. You hereby accept full responsibility for any
                    consequences that may arise from your use of the Platform or
                    availing of Services, and expressly agree and acknowledge that
                    Orocorp shall have absolutely no liability with respect to the
                    same.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    The Services and other products, information, materials, and
                    services provided by Orocorp are provided "as is". Orocorp
                    disclaims all warranties of any kind, express or implied,
                    arising out of the Services, including merchantability,
                    fitness for a particular purpose, title, and non-infringement,
                    and all warranties arising from course of dealing, usage, or
                    trade practice in respect to the same. Without limiting the
                    foregoing, Orocorp makes no warranty of any kind that the
                    Services, Platform, or any products or results of the use
                    thereof, will meet your or any other persons' requirements,
                    operate without interruption, achieve any intended result, be
                    compatible or work with any software, systems, or other
                    services, be secure, accurate, complete, free of harmful code
                    or error-free.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You shall be solely responsible for the activities that may
                    take place through your User Account, and you agree to use,
                    access, and enter the Platform at your sole risk.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You understand that we shall in no manner be held liable for
                    any unauthorised use of the Service or the Platform through
                    your User Account due to unauthorised access including but not
                    limited to hacking and security breaches.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You understand and agree that we do not accept any
                    responsibility or liability for any loss or damage that you
                    may suffer or incur if any information, documentation,
                    material, or data provided to avail the Services or the
                    Platform is incorrect, incomplete, inaccurate, or misleading,
                    or if you fail to disclose any material fact.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You hereby accept full responsibility for any consequences
                    that may arise from your use of the Services or the Platform,
                    and expressly agree and acknowledge that Orocorp shall have
                    absolutely no liability with respect to the same.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    To the fullest extent permissible by law, Orocorp, its
                    affiliates, and its related parties each disclaims all
                    liability to you for any loss or damage arising out of or due
                    to:
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    your use or inability to use, or availability or
                    unavailability of the Platform or Services;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    the occurrence or existence of any defect, interruption, or
                    delays in the operation or transmission of information to,
                    from, or through the Services or the Platform, communications
                    failure, theft, destruction, or unauthorised access to
                    Orocorp’s records, programmes, services, servers, or other
                    infrastructure relating to the Services or the Platform;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    the failure of the Platform to remain operational for any
                    period of time; or
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    the collection or processing of your personal information by
                    Orocorp.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You also agree and acknowledge that there can be disruption in
                    communication due to factors outside our control, including
                    but not limited to your device being switched off, incorrect
                    email address, network interruptions. You agree not to hold us
                    liable for non-delivery for any alert or any loss suffered by
                    you due to any delay, distortion or failure of communication.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You further agree and acknowledge that offers provided by us
                    may vary from user to user.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You further agree and acknowledge that we are providing no
                    guarantees and no warranties regarding online availability,
                    impressions, and click-through of the Platform, and any
                    material, information, links, or content presented on the
                    Platform. The Platform, and any material, information, links,
                    or content presented on the Platform, may be unavailable for
                    online access at various points of time.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You agree that your mobile device, mobile service provider or
                    any services that you may avail from any third party to access
                    the Platform, may incur charges and you are solely responsible
                    to bear such charges as per your agreement with such third
                    party.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You acknowledge and understand that we are not a financial
                    institution under the Applicable Laws. We are not a Lender and
                    do not provide any Credit Facilities. We have contractual
                    relationships with Lenders pursuant to which such Lenders
                    offer Credit Facilities to the Borrowers.
                  </font>
                </li>
                <li>Intellectual Property</li>
                <li>
                  <font color="#909090">
                    All rights, title, and interest in and to the Platform and/or
                    Services, including text, graphics, software, photographs and
                    other images, videos, sounds, trademarks, and service marks
                    are owned by or otherwise licensed to us. Subject to your
                    compliance with these Terms, we grant you a non-exclusive,
                    non-transferable, non-sublicensable, royalty-free, revocable,
                    and limited licence to use the Services in accordance with
                    these Terms.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    All names, whether appearing with the trademark symbol or not,
                    are trademarks that belong to us unless otherwise stated by
                    us. The use or misuse of these trademarks or any other
                    materials, except as permitted in these Terms, is expressly
                    prohibited and may be in violation of copyright law, trademark
                    law, and any other Applicable Law.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    The contents of this Platform are subject to copyright
                    protection. The contents of the Platform shall not be copied,
                    recopied, reproduced, or otherwise redistributed. You shall
                    not copy, display, download, distribute, modify, reproduce,
                    republish, or retransmit any information, text, or documents
                    contained in this Platform or any portion thereof in any
                    electronic medium or in hard copy, or create any derivative
                    work based on such images, texts or documents, without our
                    express written consent or as otherwise permitted in these
                    Terms.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Orocorp may request you to submit suggestions and other
                    feedback, including bug reports, relating to the Services or
                    the Platform, from time to time
                    <font color="#454545">(“Feedback”).</font> Orocorp may freely
                    use, copy, disclose, publish, display, distribute, and exploit
                    the Feedback without any payment of royalty, acknowledgement,
                    prior consent, or any other form of restriction arising out of
                    your intellectual property rights. You hereby waive any rights
                    you may have that arise out of such Feedback and agree to
                    execute such documentation as Orocorp may request to give
                    effect to Orocorp’s rights under this Clause.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Except as stated in these Terms, nothing in these Terms should
                    be construed as conferring any right in or license to our or
                    any third party’s intellectual property rights.
                  </font>
                </li>
                <li>Indemnity</li>
                <li>
                  <font color="#909090">
                    The User hereby agrees to defend and indemnify Orocorp, and
                    its affiliates, subsidiaries, officers, directors, agents,
                    assigns, licensors, employees, representatives and suppliers
                    harmless from and against any action, liability, cost, claim,
                    loss, damage, demand, lawsuit, judicial proceeding or expense
                    (including, without limitation, from all damages, liabilities,
                    settlements, costs and attorneys’ fees) suffered or incurred
                    if directly or indirectly arising from or relating to:
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    acts, commissions or omissions, errors, misrepresentations,
                    misconduct, negligence, fraud, forgery, dishonesty, violation
                    attributable to you, or any third party who may use your User
                    Account, your access to the Platform and the Services and your
                    use of the Platform and the Services in violation of these
                    Terms
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    contravention of any Applicable Law.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    any claim from any authority or any third party as a result of
                    any action or inaction on your part, including but not limited
                    to a breach of these Terms or any acts committed beyond the
                    scope of these Terms.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You shall extend all cooperation to us, in our defence of any
                    proceedings that may be initiated against us due to breach of
                    your obligations or covenants under these Terms, including in
                    any proceedings by a regulator or the Lender.
                  </font>
                </li>
                <li>Limitation of Liability</li>
                <li>
                  <font color="#909090">
                    Notwithstanding anything to the contrary contained herein,
                    neither Orocorp nor any of its affiliates or related parties
                    shall have any liability to you or any third party for any
                    indirect, incidental, special, or consequential damages or any
                    loss of revenue or profits arising under, directly or
                    indirectly, or relating, in any manner whatsoever, to these
                    Terms, including any action taken by any authority.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Notwithstanding any provision to the contrary, Orocorp’s
                    maximum aggregate liability to you under the Terms or
                    otherwise for any loss in connection with the Platform or a
                    Service shall be limited at INR 10,000.
                  </font>
                </li>
                <li>Governing Law and Dispute Resolution</li>
                <li>
                  <font color="#909090">
                    These Terms shall be governed by and construed and enforced in
                    accordance with the laws of India. Subject to Clause 13.2
                    below, courts in Chennai, India shall have exclusive
                    jurisdiction over all issues arising out of these Terms or the
                    use of the Services.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Any disputes arising in respect of or in relation to these
                    Terms shall be resolved by arbitration at Chennai in
                    accordance with the provisions of the Indian Arbitration and
                    Conciliation Act, 1996 as may be amended, or its re-enactment.
                    Within 30 (thirty) days of the issue of a notice of dispute,
                    Orocorp and you shall mutually agree on the appointment of a
                    sole arbitrator. If such mutual agreement is not arrived at
                    within the aforesaid 30 (thirty) days period, Orocorp and you
                    shall appoint such sole arbitrator in accordance with the
                    Arbitration and Conciliation Act, 1996. The seat of
                    arbitration shall be Chennai and the arbitration proceedings
                    shall be conducted in English.
                  </font>
                </li>

                <li>
                  <font color="#909090">
                    You agree to keep the arbitration confidential and not
                    disclose to any person, other than those necessary to the
                    proceedings, any information, transcripts, or award unless
                    required by Applicable Law. The decision of the arbitrator
                    shall be final and binding on us/you hereto.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You hereto agree that your consent for the resolution of the
                    dispute through arbitration shall not preclude or restrain us
                    from seeking suitable injunctive relief in appropriate
                    circumstances from courts in Chennai.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    The cost of arbitration shall be borne in a manner by us/you
                    as determined by the arbitrators.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Notwithstanding any provision to the contrary, nothing in
                    these Terms shall preclude any of Orocorp’s rights under
                    Applicable Laws.
                  </font>
                </li>
                <li>Taxes</li>
                <li>
                  <font color="#909090">
                    It is the User's responsibility to bear any taxes applicable
                    to the payments the User makes or receives in connection with
                    the use of the Platform and Services to the appropriate tax
                    authorities. We are not responsible for determining whether
                    taxes apply to your transaction, or for collecting, reporting
                    or remitting any taxes arising from any transaction.
                  </font>
                </li>
                <li>Term and termination</li>
                <li>
                  <font color="#909090">
                    These Terms shall remain in effect unless terminated in
                    accordance with the terms hereunder{" "}
                    <font color="#454545">("Term")</font>
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Orocorp may terminate your access to or use of the Services,
                    Platform, or any portion thereof, immediately and at any
                    point, at its sole discretion if you violate or breach any of
                    its obligations, responsibilities, or covenants under these
                    Terms.
                  </font>
                </li>
                <li>
                  <font color="#909090">Upon termination under this Clause:</font>
                </li>
                <li>
                  <font color="#909090">
                    the Services and/or the Platform will “time-out”;
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    you shall not be eligible to avail any features of the
                    Services and/or the Platform; and
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    these Terms shall terminate, except for those clauses that
                    expressly or are intended to survive termination or expiry.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Notwithstanding anything to the contrary contained in the
                    Terms, upon termination of your access to or use of the
                    Platform and/or the Services, you must immediately stop using
                    the Platform.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Orocorp reserves the right to cancel User Accounts that have
                    been inactive for a period of 6 months or more, and/or to
                    discontinue allowing the use of Platform and providing the
                    Services.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    The User hereby expressly agrees that the termination of these
                    Terms or de-activation of the User Account shall not affect
                    the right of payment of any outstanding amounts due from the
                    customer to Orocorp or Lenders.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You agree that you shall not be allowed to delete the User
                    Account or terminate these Terms if any of your obligations
                    under the Loan Agreement(s) are outstanding.
                  </font>
                </li>
                <li>Grievance Redressal</li>
                <li>
                  <font color="#909090">
                    For sharing any grievance or raising any queries, please
                    contact{" "}
                    <a href="mailto:grievance@orocorp.in" style={linkStyle}>
                      grievance@orocorp.in
                    </a>
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    For every complaint/grievance registered by you on the
                    Platform or the contact details provided above, a ticket
                    number shall be provided to you. Using such ticket number, you
                    may track and monitor the status of your complaint/grievance.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Further, in case you do not receive a satisfactory response
                    from us within 30 days from the date of communication of your
                    complaints/grievances, you may contact the Grievance Redressal
                    Officer using the details provided below:
                  </font>
                </li>
              </font>
            </ol>
            <p>
              Mr Mohammed Kabir<br></br>Grievance Officer<br></br>Orocorp
              Technologies Private Limited<br></br>12/1, Varadappan Street, West
              Mambalam, Chennai 600-033<br></br>Email:
              <a href="mailto:grievances@orocorp.in" style={linkStyle}>
                grievances@orocorp.in
              </a>
              <br></br>Ph: 080-46808068<br></br>
              <a href="https://oromoney.in/" style={linkStyle}>
                https://oromoney.in/
              </a>
            </p>
            <ol>
              <font color="#454545">
                <li>Miscellaneous</li>
                <li>
                  <font color="#909090">
                    The User shall not assign or otherwise transfer rights or
                    obligations under these Terms.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Orocorp may assign its rights and duties under these Terms
                    without any such assignment being considered a change to these
                    Terms and without any notice to the User.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    The User understands and agrees that no joint venture,
                    partnership, employment or agency relationship exists between
                    the User and Orocorp as a result of these Terms or on account
                    of use of the Platform or availing of the Services.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    All information shared by Orocorp with the User for the
                    purpose of providing the Services or allowing the use of
                    Platform shall be considered confidential. The following are
                    the exceptions to this clause: (a) information already in
                    public domain, and (b) such information as is required to be
                    disclosed by the disclosing party under any laws, rules or
                    regulations or pursuant to the order or direction, of any
                    Court, authority, tribunal or forum.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Enforcement of these Terms is solely in our discretion and
                    failure to enforce a provision in some instances does not
                    constitute a waiver of our right to enforce such a provision
                    in other instances.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    If any provision of these Terms is determined by any court or
                    other competent authority to be unlawful or unenforceable, the
                    other provisions of these Terms will continue to be in effect.
                    If any unlawful or unenforceable provision would be lawful or
                    enforceable if part of it were deleted, that part will be
                    deemed to be deleted, and the rest of the provisions will
                    continue to be in effect (unless that would contradict the
                    clear intention of the clause, in which case the entirety of
                    the relevant provision will be deemed to be deleted).
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    No third party shall have any rights to enforce the Terms
                    contained herein.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    We may provide you with translated versions of these Terms
                    solely to assist you with understanding these in greater
                    detail. The English version of these Terms shall be
                    controlling in all respects. In the event of any inconsistency
                    between the English version of these Terms and any translated
                    version, the terms of the English version shall prevail.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Any notices or other communications that the User wishes to
                    send to Orocorp may be addressed by email on{" "}
                    <a href="mailto:support@orocorp.in" style={linkStyle}>
                      support@orocorp.in
                    </a>
                    . Any notices to the User shall be sent by Orocorp to the
                    registered email ID of the User.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    You agree that we shall not be liable for any breach of these
                    Terms if such breach is caused by an event that is
                    unforeseeable and beyond our reasonable control (such as,
                    depending on the circumstances, unavailability of any
                    communication system, breach or virus in our system, sabotage,
                    fire, flood, explosion, acts of God, civil commotion, strikes
                    or industrial action of any kind, riots, insurrection, war,
                    acts of government, unauthorised access to computer data and
                    storage devices, computer crashes and regulatory or government
                    actions(“Force Majeure Event”).
                    In such circumstances, we will be entitled to a reasonable
                    extension of time to perform our obligations.
                  </font>
                </li>
                <li>
                  <font color="#909090">
                    Orocorp reserves the right at any time to modify these Terms and to add/introduce Additional Terms and Conditions on the use of the Services and the Platform. If you choose to continue using the Services and the Platform after such modifications, it will be considered as your acceptance of the modified Terms. In the event you refuse to accept such changes, you shall stop using the Platform. We also reserve the right to suspend or withdraw or restrict the availability of all or any part of our Platform or the Services for business and operational reasons. Your use of the Platform shall indicate that you have provided consent to automatically receive updates such as bug fixes, patches, enhanced functions, missing plug-ins and new versions (collectively, “Updates”), for the purpose of effective delivery of the Services. Please note that your continued use of the Platform following such Updates would mean deemed acceptance by you of the same.
                  </font>
                </li>
              </font>
            </ol>
          </div>
      </Textbox>
      </div>
      </div></>
  );
};

export default AboutPage;
